# Generated by Django 4.2.2 on 2023-07-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
