# Generated by Django 4.2.2 on 2023-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_numper',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
