# Generated by Django 4.2.2 on 2023-07-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_numper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
