# Generated by Django 4.2.2 on 2023-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_slug_alter_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='apply/')),
                ('cover_letter', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
