# Generated by Django 4.2.2 on 2023-06-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='criated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
