# Generated by Django 4.2.2 on 2023-07-03 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0013_apply_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
