# Generated by Django 4.2.2 on 2023-07-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_job_country_alter_job_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
